import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="relative z-20 p-5">
            <header className="flex justify-between pb-4 border-white border-b-2 mb-9">
                <p className="text-4xl">SAIT</p>
                <NavBar />
            </header>
            {children}
        </div>
    );
}
