import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className} m-5`}>
                <header className="flex justify-between pb-4 border-black border-b-2 mb-9">
                    <p className="text-4xl">SAIT</p>
                    <NavBar />
                </header>
                {children}
            </body>
        </html>
    );
}
