import type { Metadata } from "next";
import "./globals.css";
import Image from 'next/image'
import image from '../../public/abc.webp'
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable
      )} relative min-h-[100vh] `}>
        <div className="absolute bg-blue-800 inset-0"></div>
        <div className="relative z-20 p-5">
          {children}
        </div>
        <div className="pt-10">
          <p className="text-black text-center relative z-20 py-5 bg-green-400">SAIT logo from
            <Link className=" ml-1 underline" href={"https://www.google.com/url?sa=i&url=https%3A%2F%2Fcollegedunia.com%2Fcanada%2Fcollege%2F585-sait-polytechnic-calgary&psig=AOvVaw2AL8vGAeTmP3eVZJZjgDDX&ust=1713298464861000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCKDg76qExYUDFQAAAAAdAAAAABAP"}>
              source
            </Link>
          </p>
        </div>
      </body>
    </html>
  );
}
