import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=
        "min-h-screen relative">
        <div className="absolute bg-blue-800 inset-0"></div>
        <div className="relative z-20 p-5">
          {children}
        </div>
      </body>
    </html>
  );
}
